CREATE TABLE Usuario
(
	CPF VARCHAR(255)NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	DATA_NASCIMENTO TIMESTAMP NOT NULL,
	NUMERO_CARTAO VARCHAR(255) NOT NULL,
	SALDO_CARTAO VARCHAR(255) NOT NULL,
	ESTADO_CARTAO VARCHAR(255) NOT NULL,
	TIPO_CARTAO VARCHAR(255) NOT NULL,
	VALIDADE_CARTAO TIMESTAMP NOT NULL,
	PRIMARY KEY (CPF)
)

CREATE TABLE Estacao
(
	ID_ESTACAO VARCHAR(255) NOT NULL,
	QTD_ARMAZENAMENTO VARCHAR(255) NOT NULL,
	QTD_OCUPADA VARCHAR(255) NOT NULL,
	CEP VARCHAR(255) NOT NULL,
	NUM VARCHAR(255) NOT NULL,
	RUA VARCHAR(255) NOT NULL,
	BAIRRO VARCHAR(255) NOT NULL,
	CIDADE VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID_ESTACAO)
)

CREATE TABLE Fornecedor
(
	CNPJ VARCHAR(255) NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	PRIMARY KEY (CNPJ)
)

CREATE TABLE Bicicleta
(
	ID_BICICLETA VARCHAR(255) NOT NULL,
	TAMANHO VARCHAR(255) NOT NULL,
	MODELO VARCHAR(255) NOT NULL,
	ESTADO_CONSERVACAO VARCHAR(255) NOT NULL,
	ATIVA BOOLEAN NOT NULL,
	CNPJ_FORNECEDOR VARCHAR(255) NOT NULL,
	ID_ESTACAO VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID_BICICLETA),
	FOREIGN KEY (CNPJ_FORNECEDOR) REFERENCES FORNECEDOR(CNPJ),
	FOREIGN KEY (ID_ESTACAO) REFERENCES ESTACAO(ID_ESTACAO)
)

CREATE TABLE Conserta
(
	ID_BICICLETA VARCHAR(255) NOT NULL,
	CNPJ_FORNECEDOR VARCHAR(255) NOT NULL,
	DATA_INICIO TIMESTAMP NOT NULL,
	DATA_FIM TIMESTAMP,
	PRAZO TIMESTAMP NOT NULL,
	PRIMARY KEY (ID_BICICLETA, CNPJ_FORNECEDOR, DATA_INICIO),
	FOREIGN KEY (ID_BICICLETA) REFERENCES BICICLETA(ID_BICICLETA),
	FOREIGN KEY (CNPJ_FORNECEDOR) REFERENCES FORNECEDOR(CNPJ)
)

CREATE TABLE Armazena
(
	ID_ESTACAO VARCHAR(255) NOT NULL,
	ID_BICICLETA VARCHAR(255) NOT NULL,
	DATA_INICIO VARCHAR(255) NOT NULL,
	DATA_FIM VARCHAR(255),
	PRIMARY KEY (ID_BICICLETA, ID_ESTACAO, DATA_INICIO),
	FOREIGN KEY (ID_BICICLETA) REFERENCES BICICLETA(ID_BICICLETA),
	FOREIGN KEY (ID_ESTACAO) REFERENCES ESTACAO(ID_ESTACAO)
)

CREATE TABLE ALUGUEL
(
	ID_ALUGUEL VARCHAR(255) NOT NULL,
	ID_BICICLETA VARCHAR(255) NOT NULL,
	CPF_USUARIO VARCHAR(255) NOT NULL,
	DATA_INICIO TIMESTAMP NOT NULL,
	DATA_FIM TIMESTAMP,
	ID_ESTACAO_INICIO VARCHAR(255) NOT NULL,
	ID_ESTACAO_FIM VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID_ALUGUEL),
	FOREIGN KEY (ID_BICICLETA) REFERENCES BICICLETA(ID_BICICLETA),
	FOREIGN KEY (CPF_USUARIO) REFERENCES USUARIO(CPF),
	FOREIGN KEY (ID_ESTACAO_INICIO) REFERENCES ESTACAO(ID_ESTACAO),
	FOREIGN KEY (ID_ESTACAO_FIM) REFERENCES ESTACAO(ID_ESTACAO)
)
